version: "3.9"
services:
  newgreedy:
    build: .
    ports:
      - "3456:3456"
      - "8080:8080"
    volumes:
      - ./stats.json:/app/stats.json
      - ./newgreedy.log:/app/newgreedy.log
    restart: unless-stopped
