version: "3.8"
services:
  newgreedy:
    build: .
    ports:
      - "3456:3456"
      - "8080:8080"
    volumes:
      - ./config.ini:/app/config.ini
      - ./stats.json:/app/stats.json
    restart: unless-stopped
